# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdUevn5GxYO4XJDCxrL72f8LW-uTWhT1
"""

# # Install streamlit using pip in the notebook cell.
# !pip install streamlit

# Import necessary libraries.
import streamlit as st

# Rest of your code...
st.title("Calculadora Solar")

st.write("Preencha os dados abaixo:")

potencia_modulo = st.number_input("Potência de cada módulo (W)", min_value=100, max_value=700, value=450)
quantidade_modulos = st.number_input("Quantidade de módulos", min_value=1, max_value=1000, value=10)

potencia_total = potencia_modulo * quantidade_modulos

st.markdown(f"### Potência total estimada: **{potencia_total / 1000:.2f} kW**")
